name: Check unit test

on:
  push:
    branches:
      - master

jobs:
  validate:
    name: "Unit Test and Bundle Validation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installing databricks CLI
        uses: databricks/setup-cli@main

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements-dev.txt

      - name: Run unit tests check
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          python -m pytest
      - run: databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
